kind: pipeline
name: default
steps:
  - name: test
    image: python
    commands:
      - pip install pipenv
      - pipenv install
      - pipenv run gitlint
      - pipenv run pylint setup.py updater.py
      - pipenv run python -m unittest